linnovate/root

packages/custom/icu/app.js, packages/custom/icu/public/assets/css/_detailspane.scss, packages/custom/icu/public/assets/css/_display-by.scss, packages/custom/icu/public/assets/css/_middlepane.scss, packages/custom/icu/public/assets/css/_sidepane.scss, packages/custom/icu/public/assets/css/_variables.scss, packages/custom/icu/public/assets/css/styles.css, packages/custom/icu/public/assets/css/styles.scss, packages/custom/icu/public/components/display-by/display-by.html, packages/custom/icu/public/components/display-by/display-by.js, packages/custom/icu/public/components/middlepane/middlepane.html, packages/custom/icu/public/components/sidepane/sidepane.directive.js, packages/custom/icu/public/components/sidepane/sidepane.html, packages/custom/icu/public/components/user-details/user-details.js, packages/custom/icu/public/components/user-list/user-list.js
Implement disaply by directive with conditional content
Fix navigation issue on people page
=> Change sizes and colors to comply with design

packages/custom/icu/public/app/app.js, packages/custom/icu/public/assets/css/_task-list.scss, packages/custom/icu/public/components/data/tasks/tasks.service.js, packages/custom/icu/public/components/row-types/task-row.html, packages/custom/icu/public/components/task-details/task-details.js, packages/custom/icu/public/components/task-list/task-list.directive.js, packages/custom/icu/public/components/task-list/task-list.directive.template.html, packages/custom/icu/public/components/task-list/task-list.html
Binding task title between task list and task details
=> Editing tasks from list, creating task from list

packages/custom/general/server/providers/crud.js, packages/custom/icu/public/assets/css/_detailspane.scss, packages/custom/icu/public/assets/css/_middlepane.scss, packages/custom/icu/public/assets/css/_tabs-activities.scss, packages/custom/icu/public/assets/css/_task-details.scss, packages/custom/icu/public/assets/css/_task-list.scss, packages/custom/icu/public/assets/css/_variables.scss, packages/custom/icu/public/assets/css/mixins/_table.scss, packages/custom/icu/public/components/middlepane/middlepane.directive.js, packages/custom/icu/public/components/middlepane/middlepane.html, packages/custom/icu/public/components/row-types/task-row.html, packages/custom/icu/public/components/task-details/task-details.js, packages/custom/icu/public/components/task-list/task-list.directive.js, packages/custom/icu/public/components/task-list/task-list.directive.template.html, packages/custom/icu/public/components/task-list/task-list.html
Should be merged after API fixes.
Based on #39
=> Task deleting

packages/custom/icu/app.js, packages/custom/icu/public/app/app.js, packages/custom/icu/public/assets/css/_discussion-details.scss, packages/custom/icu/public/assets/css/_entity-list.scss, packages/custom/icu/public/assets/css/_tabs-tasks.scss, packages/custom/icu/public/assets/css/styles.scss, packages/custom/icu/public/components/data/discussions/discussions.service.js, packages/custom/icu/public/components/discussion-details/discussion-details.html, packages/custom/icu/public/components/discussion-details/discussion-details.js, packages/custom/icu/public/components/discussion-details/tabs/tasks/tasks.html, packages/custom/icu/public/components/discussion-details/tabs/tasks/tasks.js, packages/custom/icu/public/components/discussion-list/discussion-list.directive.js, packages/custom/icu/public/components/discussion-list/discussion-list.directive.template.html, packages/custom/icu/public/components/discussion-list/discussion-list.html, packages/custom/icu/public/components/discussion-list/discussion-list.js, packages/custom/icu/public/components/row-types/discussion-row.html, packages/custom/icu/public/components/row-types/row.directive.js, packages/custom/icu/public/components/row-types/task-row.html, packages/custom/icu/public/components/task-details/task-details.js, packages/custom/icu/public/components/task-list/task-list.directive.js, packages/custom/icu/public/components/task-list/task-list.directive.template.html, packages/custom/icu/public/components/task-list/task-list.html, packages/custom/icu/public/components/task-list/task-list.js
=> Discussion details tabs

packages/custom/icu/public/components/task-details/task-details.html, packages/custom/icu/public/components/task-details/task-details.js, packages/custom/icu/public/components/task-list-directive/task-list.directive.js, packages/custom/icu/public/components/task-list-directive/task-list.directive.template.html
Won't work until this task is done https://trello.com/c/otoadZcu/151-api-consistency
=> Fix project change from task details

packages/custom/icu/app.js, packages/custom/icu/public/assets/css/_detailspane.scss, packages/custom/icu/public/components/autofocus/autofocus.directive.js, packages/custom/icu/public/components/discussion-details/discussion-details.html, packages/custom/icu/public/components/notifications-header/header.directive.js, packages/custom/icu/public/components/project-details/project-details.html, packages/custom/icu/public/components/row-types/task-row.html, packages/custom/icu/public/components/task-list/task-list.js
fix description placeholder
implement tabindex
disable multiple lines in title
fix redirect issue
=> Change redirect aftetr P/D creation

packages/custom/icu/public/components/discussion-list-directive/discussion-list.directive.js, packages/custom/icu/public/components/discussion-list-directive/discussion-list.directive.template.html, packages/custom/icu/public/components/discussion-list/discussion-list.js, packages/custom/icu/public/components/project-list-directive/project-list.directive.js, packages/custom/icu/public/components/project-list-directive/project-list.directive.template.html, packages/custom/icu/public/components/project-list/project-list.js, packages/custom/icu/public/components/task-list-directive/task-list.directive.js, packages/custom/icu/public/components/task-list-directive/task-list.directive.template.html, packages/custom/icu/public/components/task-list/task-list.js
Select entity after sorting applied
=> Fix first selected entity in list

packages/custom/icu/public/components/data/cacheDecorator.js
Even if server returns it after delete
=> Remove deleted entity from list

packages/custom/icu/public/components/row-types/task-row.html, packages/custom/icu/public/components/task-list-directive/task-list.directive.js, packages/custom/icu/public/components/task-list-directive/task-list.directive.template.html
Fix autocomplete for attached tasks
=> Implement hiding autocomplete popup on blur

packages/custom/icu/public/assets/css/_detailspane.scss, packages/custom/icu/public/assets/css/_tabs-activities.scss, packages/custom/icu/public/components/detailspane/detailspane.directive.js, packages/custom/icu/public/components/tabs/activities/activities.html
On mouse hover on tabs, their content changes its height
Description become smaller
=> Change details tabs behavior

packages/custom/icu/public/assets/css/_detailspane.scss, packages/custom/icu/public/components/task-list-directive/task-list.directive.js, packages/custom/icu/public/components/task-list-directive/task-list.directive.template.html
Cahnge default styles for details pane
=> Fix autocomplete selection

packages/custom/icu/public/components/discussion-details/tabs/tasks/tasks.controller.js, packages/custom/icu/public/components/discussion-details/tabs/tasks/tasks.html, packages/custom/icu/public/components/project-details/tabs/tasks/tasks.controller.js, packages/custom/icu/public/components/project-details/tabs/tasks/tasks.html, packages/custom/icu/public/components/tabs/tasks/tasks.directive.js, packages/custom/icu/public/components/tabs/tasks/tasks.html, packages/custom/icu/public/components/user-details/tabs/tasks/tasks.html
=> Enable default sorting in tasks tab

packages/custom/icu/public/app/app.js, packages/custom/icu/public/assets/css/styles.scss, packages/custom/icu/public/components/middlepane/middlepane.directive.js, packages/custom/icu/public/components/search-list/search-list.directive.js
clearing search cleans out results, focus does not jump anymore
=> Searchbar functionality

packages/custom/icu/public/assets/css/_sidepane.scss, packages/custom/icu/public/components/sidepane/sidepane.html
expand/collapse for main categories in sidepane
=> sidepane expand collapse functionality

packages/custom/icu/public/components/task-list-directive/task-list.directive.js
Code needs to keep same reference everyevery to ensure working
binding
=> Modify given array of tasks

packages/custom/discussions/server/routes/discussions.js, packages/custom/icu/public/app/app.js, packages/custom/icu/public/components/data/discussions/discussions.service.js, packages/custom/icu/public/components/data/projects/projects.service.js, packages/custom/icu/public/components/discussion-list-directive/discussion-list.directive.js, packages/custom/icu/public/components/discussion-list/discussion-list.html, packages/custom/icu/public/components/discussion-list/discussion-list.js, packages/custom/icu/public/components/project-details/project-details.js, packages/custom/icu/public/components/project-list-directive/project-list.directive.js, packages/custom/icu/public/components/project-list/project-list.html, packages/custom/icu/public/components/project-list/project-list.js, packages/custom/icu/public/components/sidepane/sidepane.directive.js, packages/custom/icu/public/components/task-details/task-details.js, packages/custom/icu/public/components/task-list/task-list.js, packages/custom/projects/server/routes/projects.js
For tasks, projects and discussions
=> Client side pagination/sorting

packages/custom/icu/public/app/app.js
Still have same issue as with task, where this entity gets
disconnected from list
=> Fix getting entity by id from page 2 and onwards

bower.json
update bower.json to prevent error on bower install
=> further #198 issue, 

packages/custom/icu/app.js, packages/custom/icu/public/assets/css/_display-by.scss, packages/custom/icu/public/assets/locales/en/translation.json, packages/custom/icu/public/assets/locales/he/translation.json, packages/custom/icu/public/components/display-by/display-by.html, packages/custom/icu/public/components/icu/icu.html, packages/custom/icu/public/components/middlepane/middlepane.directive.js, packages/custom/icu/public/components/middlepane/middlepane.html, packages/custom/icu/public/components/notify/notify.service.js, packages/custom/icu/public/components/sidepane/sidepane.directive.js
=> Sidebar design

packages/custom/icu/public/components/display-by/display-by.html
added assigners to search active submenu
=> search active added assigners

packages/custom/icu/public/components/display-by/display-by.js, packages/custom/icu/public/components/sidepane/sidepane.directive.js, packages/custom/icu/public/components/sidepane/sidepane.html
=> fixed issues #558 #559

packages/custom/icu/public/components/display-by/display-by.html
=> fixed issue #562

packages/custom/icu/public/assets/css/_sidepane.scss
=> fixed issue #582

packages/custom/icu/public/components/sidepane/sidepane.directive.js
of reloading after selecting item in submenu of 'settings'
=> fixed issue #574-3

packages/custom/icu/public/components/data/search/search.service.js, packages/custom/icu/public/components/sidepane/sidepane.directive.js, packages/custom/icu/public/components/sidepane/sidepane.html
shows url 'search' only by search tab click and shows no results found,  #592-3
=> fixed issue #592-3 shows url 'search' only by search tab click and shows

packages/custom/icu/public/assets/css/_display-by.scss, packages/custom/icu/public/components/display-by/display-by.html
fixed issue #604 now shows folders from office
=> fixed issue #604 now shows folders from office

packages/custom/icu/public/assets/css/_entity-list.scss
fixed issue #605 now shows projects title in middlepane
=> fixed issue #605 now shows projects title in middlepane

packages/custom/icu/public/components/data/projects/projects.service.js
fixed adding assigner to subproject
=> added MeanSocket service to projects service

packages/custom/icu/public/assets/css/_display-by.scss, packages/custom/icu/public/components/display-by/display-by.html, packages/custom/icu/public/components/display-by/display-by.js
https://github.com/linnovate/root/issues/630 fixed
=> folderslist hotfix

packages/custom/icu/public/assets/css/styles.scss, packages/custom/icu/public/components/data/permissions/permissions.service.js, packages/custom/icu/public/components/discussion-details/discussion-details.html, packages/custom/icu/public/components/discussion-details/discussion-details.js, packages/custom/icu/public/components/project-details/project-details.html, packages/custom/icu/public/components/project-details/project-details.js, packages/custom/icu/public/components/task-details/task-details.html, packages/custom/icu/public/components/task-details/task-details.js
fixed disabled recycled entity button 'un-delete' to editor
=> disabled un-delete Project fixed

packages/custom/icu/public/components/display-by/display-by.js
fixed console err usage users service in submenu
=> fixed users service usage in submenu

packages/custom/icu/public/components/data/permissions/permissions.service.js, packages/custom/icu/public/components/discussion-details/discussion-details.html, packages/custom/icu/public/components/discussion-details/discussion-details.js, packages/custom/icu/public/components/officeDocument-details/officeDocument-details.html, packages/custom/icu/public/components/officeDocument-details/officeDocument-details.js, packages/custom/icu/public/components/project-details/project-details.html, packages/custom/icu/public/components/project-details/project-details.js, packages/custom/icu/public/components/tabs/documents/documents.directive.js, packages/custom/icu/public/components/tabs/tasks/tasks.directive.js, packages/custom/icu/public/components/task-details/task-details.html, packages/custom/icu/public/components/task-details/task-details.js
-allowed to switch tabs when recycled.
=> disabled subs in recycled. disabled select project when recycled.

packages/custom/icu/public/assets/css/_detailspane.scss, packages/custom/icu/public/assets/css/_officeDocument-details.scss, packages/custom/icu/public/assets/css/_sub-tasks.scss
watcher couldn't use detailspane header to create entities(fixed)
=> disabled top-header for watcher fix

packages/custom/icu/public/components/display-by/display-by.html, packages/custom/icu/public/components/display-by/display-by.js, packages/custom/icu/public/components/sidepane/sidepane.directive.js
fixed clearing filters for search submenu
=> fixed 'clear' buttons

packages/custom/icu/public/components/project-details/project-details.html, packages/custom/icu/public/components/project-details/project-details.js
https://github.com/linnovate/root/issues/727
=> fixed erorr on adding entity to favorite

packages/custom/icu/public/components/project-list/project-list.html, packages/custom/icu/public/components/project-list/project-list.js
https://github.com/linnovate/root/issues/752
=> fixed showing of parent name of subprojects

packages/custom/icu/public/components/officeDocument-details/officeDocument-details.html
https://github.com/linnovate/root/issues/763
=> fixed unavailable button 'receive' for receiver in office documents

packages/custom/icu/public/components/project-list-directive/project-list.directive.js
https://github.com/linnovate/root/issues/772
=> fixed creation of sub project by 'ENTER'

packages/custom/icu/public/components/row-types/discussion-row.html
https://github.com/linnovate/root/issues/777
=> fixed meeting title editable in middlepane UI for viewers

packages/custom/icu/public/components/folder-list-directive/folder-list.directive.js, packages/custom/icu/public/components/office-list-directive/office-list.directive.js, packages/custom/icu/public/components/officeDocument-list-directive/officeDocument-list.directive.js, packages/custom/icu/public/components/project-list-directive/project-list.directive.js, packages/custom/icu/public/components/task-list-directive/task-list.directive.js
"Cannot read property 'split' of undefined"
=> fixed console error after creating many entities,

packages/custom/icu/public/components/modal-directive/modal.directive.js, packages/custom/icu/public/components/project-details/project-details.js
https://github.com/linnovate/root/issues/801
=> fixed transition to another state on changing notifications params, resetting avatar

packages/custom/icu/public/components/data/projects/projects.service.js, packages/custom/icu/public/components/data/tasks/tasks.service.js, packages/custom/icu/public/components/project-details/project-details.js, packages/custom/icu/public/components/task-details/task-details.js
https://github.com/linnovate/root/issues/802
=> fixed showing subtasks/subprojects after recycling/unrecycling them

packages/custom/icu/public/assets/css/_sidepane.scss
https://github.com/linnovate/root/issues/805
=> fixed submenu height

packages/custom/icu/public/components/task-options/task-options.js
https://github.com/linnovate/root/issues/818
=> fixed showing recycled entities in 'watched tasks' section

packages/custom/icu/public/assets/css/_project-details.scss, packages/custom/icu/public/assets/css/_task-details.scss
https://github.com/linnovate/root/issues/815
=> fixed showing names in adding watchers dropdown

packages/custom/icu/public/assets/css/_task-details.scss
https://github.com/linnovate/root/issues/758
=> fixed dropdown selection of office in templateDocs

packages/custom/icu/public/components/notifications-header/header.directive.js
https://github.com/linnovate/root/issues/833
=> fixed updating title of project entity,created from discussion

packages/custom/icu/public/assets/css/_entity-list.scss, packages/custom/icu/public/assets/css/_middlepane.scss
https://github.com/linnovate/root/issues/868
=> fixed bug, styles of title html tags showing in the middle pane list

packages/custom/icu/public/assets/css/_panes.scss
https://github.com/linnovate/root/issues/866
=> fixed showing elements in middle pane list in pre-view mode to print

packages/custom/icu/public/components/officeDocument-list-directive/officeDocument-list.directive.js, packages/custom/icu/server/controllers/documents.js
https://github.com/linnovate/root/issues/863
=> fixed Creating a new document doesn't show its folder

packages/custom/icu/public/components/sidepane/sidepane.directive.js
https://github.com/linnovate/root/issues/880
=> fixed showing search results on turning off recycle button

packages/custom/icu/public/components/sidepane/sidepane.directive.js, packages/custom/icu/public/components/sidepane/sidepane.html
fixed showing search results after reopening 'search' menu tab,
refactoring
https://github.com/linnovate/root/issues/859
=> fixed hiding search results on clicking 'search' menu tab once again,

packages/custom/icu/public/components/task-options/task-options.js
818 for dev
https://github.com/linnovate/root/issues/818
=> removed the deleted items from all the home page buttons.

packages/custom/icu/public/components/folder-list/folder-row.html
https://github.com/linnovate/root/issues/925
=> removed html tags from office tag in folder list (main pane)

packages/custom/icu/public/components/officeDocument-details/officeDocument-details.js
added check to add all folder's watchers to officeDocument
https://github.com/linnovate/root/issues/908
=> removed console error on adding folder to officeDocument

packages/custom/icu/public/assets/css/_display-by.scss, packages/custom/icu/public/assets/css/_sidepane.scss
https://github.com/linnovate/root/issues/934
=> fixed scrolling in submenu

packages/custom/icu/public/components/discussion-list/discussion-list.js, packages/custom/icu/public/components/folder-list/folder-list.js, packages/custom/icu/public/components/office-list/office-list.js, packages/custom/icu/public/components/officeDocument-list/officeDocument-list.js, packages/custom/icu/public/components/project-list/project-list.js, packages/custom/icu/public/components/task-list/task-list.js
https://github.com/linnovate/root/issues/933
=> fixed bug renaming any entity produces bad request

packages/custom/icu/public/assets/css/_display-by.scss, packages/custom/icu/public/components/display-by/display-by.html
added scrolling to folders list, to show all folders
https://github.com/linnovate/root/issues/934
=> fixed folders list showing all folders (scrolling) + UI

packages/custom/icu/public/assets/css/_detailspane.scss, packages/custom/icu/public/components/task-options/task-options.html
https://github.com/linnovate/root/issues/960
=> fixed crashed scrolling styles

packages/custom/icu/public/components/folder-details/folder-details.js
https://github.com/linnovate/root/issues/967
=> fixed removing folder

packages/custom/icu/public/components/sidepane/sidepane.directive.js
fixed https://github.com/linnovate/root/issues/799 2 and 3 items
=> fixed showing in printer mode only first items from list

packages/custom/icu/public/components/entity-list/entity-list.js, packages/custom/icu/public/components/folder-list/folder-list.js
https://github.com/linnovate/root/issues/976
=> creating folder from office creating folder without binding to his parent

packages/core/system/server/controllers/index.js, packages/custom/icu/public/components/row-types/row.directive.js
@nevos talk to @manmorc first
https://github.com/linnovate/root/issues/871
=> removed hardcoded language dependencies in code

packages/custom/icu/public/components/entity-list/regions/list.html
https://github.com/linnovate/root/issues/911
=> fixed redirecting from home page

config/env/all.js, packages/custom/icu/public/assets/css/_avatar.scss, packages/custom/icu/public/assets/css/_detailspane.scss, packages/custom/icu/public/assets/css/entity-details/_detail-members.scss, packages/custom/icu/public/assets/css/entity-details/_detail-tags.scss, packages/custom/icu/public/components/avatar/avatar.html, packages/custom/icu/public/components/avatar/avatar.js, packages/custom/icu/public/components/data/permissions/permissions.service.js, packages/custom/icu/public/components/project-details/project-details.html, packages/custom/icu/public/components/task-details/task-details.html
refactored styles, refactored permissions
https://github.com/linnovate/root/issues/973
=> changed color for commenter,

packages/custom/icu/public/components/discussion-list/discussion-row.html, packages/custom/icu/public/components/entity-list/entity-list.js, packages/custom/icu/public/components/folder-list/folder-row.html, packages/custom/icu/public/components/office-list/office-row.html, packages/custom/icu/public/components/officeDocument-list/officeDocument-row.html, packages/custom/icu/public/components/project-list/project-row.html, packages/custom/icu/public/components/task-list/task-row.html, packages/custom/icu/public/components/templateDoc-list/templateDoc-row.html
https://github.com/linnovate/root/issues/791
=> fixed showing long titles in middle pane in develop

packages/custom/icu/public/components/discussion-details/discussion-details.js, packages/custom/icu/public/components/discussion-details/discussion-due/discussion-due.html
trouble with scheduling appear, because it will not work if there is no assignee, and the functionality to add assignee was missed
https://github.com/linnovate/root/issues/948
=> fixed schedule discussion button

packages/custom/icu/public/assets/css/_attachment-details.scss, packages/custom/icu/public/components/attachment-details/attachment-details.html, packages/custom/icu/public/components/attachment-details/attachment-details.js, packages/custom/icu/public/components/modal-directive/documentPreview/document-preview.html
https://github.com/linnovate/root/issues/921
=> fixed attachment UI, added project title

packages/custom/icu/public/assets/css/entity-details/_detail-assign.scss
https://github.com/linnovate/root/issues/998
=> fixed showing the user name/email prefix always then ellipsis

packages/custom/icu/public/assets/css/_task-details.scss, packages/custom/icu/public/assets/css/entity-details/_entity-details.scss, packages/custom/icu/public/components/project-details/project-details.html
https://github.com/linnovate/root/issues/999
=> fixed scrolling in projects details

packages/custom/icu/public/app/app.js
https://github.com/linnovate/root/issues/964
=> fixed showing button 'manage tasks' in subproject

packages/custom/icu/public/components/discussion-details/discussion-details.js
https://github.com/linnovate/root/issues/948
=> fixed changing discussion status after assigning user

packages/custom/icu/public/components/folder-details/folder-details.js, packages/custom/icu/public/components/office-details/office-details.js, packages/custom/icu/public/components/project-details/project-details.js
https://github.com/linnovate/root/issues/994
=> fixed color changing bug

packages/custom/icu/public/components/project-list/project-list.js, packages/custom/icu/public/components/project-list/project-row.html, packages/custom/icu/public/components/task-details/task-details.html
added title to project row, fixed disabling to viewer sub tasks
https://github.com/linnovate/root/issues/993
=> fixed updating subprojects in main pane,

packages/custom/icu/public/assets/locales/en/translation.json, packages/custom/icu/public/assets/locales/he/translation.json
https://github.com/linnovate/root/issues/988
=> fixed my tasks visual title bug

packages/custom/icu/public/components/discussion-details/discussion-details.js, packages/custom/icu/public/components/entity-list/entity-list.js, packages/custom/icu/public/components/folder-details/folder-details.js, packages/custom/icu/public/components/office-details/office-details.js, packages/custom/icu/public/components/officeDocument-details/officeDocument-details.js
https://github.com/linnovate/root/issues/1011
=> fixed saving color after changing favorite status

packages/custom/icu/public/assets/css/_entity-list.scss, packages/custom/icu/public/assets/css/entity-details/_detail-due.scss, packages/custom/icu/public/assets/css/mixins/_disableTextStyles.scss, packages/custom/icu/public/assets/css/styles.scss, packages/custom/icu/public/components/modal-directive/receiveModal.html
removed showing styles in middle pane, refactored scss
https://github.com/linnovate/root/issues/1003
=> fixed fixed ui bug with entering time with data in discussion due

packages/custom/icu/public/assets/css/_discussion-details.scss, packages/custom/icu/public/assets/css/_entity-list.scss, packages/custom/icu/public/assets/css/_officeDocument-details.scss, packages/custom/icu/public/assets/css/entity-details/_detail-assign.scss, packages/custom/icu/public/assets/css/entity-details/_detail-category.scss, packages/custom/icu/public/assets/css/entity-details/_detail-due.scss, packages/custom/icu/public/assets/css/entity-details/_detail-favorite.scss, packages/custom/icu/public/assets/css/entity-details/_detail-menu.scss, packages/custom/icu/public/assets/css/entity-details/_detail-status.scss, packages/custom/icu/public/assets/css/entity-details/_detail-tabs.scss, packages/custom/icu/public/assets/css/entity-details/_entity-details.scss, packages/custom/icu/public/assets/css/mixins/_disable-text-styles.scss, packages/custom/icu/public/assets/css/mixins/_golden-hover.scss, packages/custom/icu/public/assets/css/styles.scss, packages/custom/icu/public/components/officeDocument-details/officeDocument-details.html, packages/custom/icu/public/components/templateDoc-details/templateDoc-details.html
fixed disabling for user with no permissions to entity
fixed visual hover on 'summary' elements
https://github.com/linnovate/root/issues/1022
=> fixed disabling notifications-header

packages/custom/icu/public/components/officeDocument-details/officeDocument-details.html
https://github.com/linnovate/root/issues/1006
=> fixed showing wrong modal on distributed message

packages/custom/icu/public/assets/css/_attachment-details.scss, packages/custom/icu/public/assets/css/_entity-list.scss, packages/custom/icu/public/assets/css/_sub-projects.scss, packages/custom/icu/public/components/avatar/avatar.html
https://github.com/linnovate/root/issues/971
=> fixed ui bug in sub projects, in avatar, attachment

packages/custom/icu/public/components/data/officeDocuments/officeDocuments.service.js
https://github.com/linnovate/root/issues/957
=> fixed console error on updating office document title

packages/custom/icu/public/components/officeDocument-details/officeDocument-details.html
https://github.com/linnovate/root/issues/1012
=> fixed showing wrong modal on creating document from template

packages/custom/icu/public/components/modal-directive/modal.directive.js
https://github.com/linnovate/root/issues/1016
=> fixed updating avatar after changing it

packages/custom/icu/public/assets/css/_avatar.scss, packages/custom/icu/public/assets/css/_modal.scss, packages/custom/icu/public/components/modal-directive/sendDocument.html
https://github.com/linnovate/root/issues/1014
=> fixed UI bug in sending document modal

packages/custom/icu/public/assets/css/entity-details/_entity-details.scss, packages/custom/icu/public/assets/css/mixins/_disable-text-styles.scss, packages/custom/icu/public/components/discussion-details/discussion-details.html, packages/custom/icu/public/components/folder-details/folder-details.html, packages/custom/icu/public/components/folder-details/folder-details.js, packages/custom/icu/public/components/office-details/office-details.html, packages/custom/icu/public/components/officeDocument-details/officeDocument-details.html, packages/custom/icu/public/components/project-details/project-details.html, packages/custom/icu/public/components/task-details/task-details.html, packages/custom/icu/public/components/task-details/task-details.js, packages/custom/icu/public/components/templateDoc-details/templateDoc-details.html
added missed function to update folders
https://github.com/linnovate/root/issues/1033
=> fixed activating medium editor function with none-permitted user,

packages/custom/icu/public/components/sidepane/sidepane.directive.js
https://github.com/linnovate/root/issues/1036
=> fixed routing back to search shows old search results

packages/custom/icu/public/assets/css/entity-details/_detail-due.scss, packages/custom/icu/public/assets/css/entity-details/_entity-details.scss, packages/custom/icu/public/components/discussion-details/discussion-due/discussion-due.html, packages/custom/icu/public/components/discussion-details/discussion-due/discussion-due.js
fixed placeholder title position
https://github.com/linnovate/root/issues/1041
=> fixed fixed discussions, removed styles from js,

packages/custom/icu/public/app/app.js, packages/custom/icu/public/components/sidepane/sidepane.directive.js
https://github.com/linnovate/root/issues/1037
=> divided counts of found items for recycled and none-recycled entities

packages/core/users/server/routes/users.js, packages/custom/icu/public/components/data/documents/documents.service.js, packages/custom/icu/public/components/modal-directive/documentPreview/document-previewController.js, packages/custom/icu/public/components/tabs/activities/activities.directive.js, packages/custom/icu/public/components/tabs/activities/activities.html, packages/custom/icu/public/components/tabs/documents/documents.directive.js, packages/custom/icu/public/components/tabs/documents/documents.html, packages/custom/icu/server/controllers/notification.js, packages/custom/icu/server/controllers/updates.js
https://github.com/linnovate/root/issues/1013
=> fixed flow uploading document, showing document dat aafter uploading

packages/custom/icu/server/controllers/project.js
filtered search result from subprojects
https://github.com/linnovate/root/issues/993
=> fixed bug with showing sub project twice

packages/custom/icu/public/components/project-details/project-details.html, packages/custom/icu/public/components/task-details/task-details.html
https://github.com/linnovate/root/issues/929
=> enabled template button if there is no sub entities

packages/custom/icu/public/components/details-components/detail-category/detail-category.html, packages/custom/icu/public/components/details-components/detail-category/detail-category.js
https://github.com/linnovate/root/issues/1004
=> added update list of existing entities on opening selection dropdown

packages/custom/icu/public/assets/css/entity-details/_entity-details.scss, packages/custom/icu/public/components/detailspane/detailspane.html
https://github.com/linnovate/root/issues/1048
=> fixed translate new entity

packages/custom/icu/public/components/discussion-details/discussion-details.js, packages/custom/icu/public/components/project-details/project-details.js
https://github.com/linnovate/root/issues/1063
(cherry picked from commit d2a33db)
=> fixed errors on adding tags to projects and discussions

packages/custom/icu/public/components/officeDocument-details/officeDocument-details.html
https://github.com/linnovate/root/issues/1076
=> fixed saving attachment

packages/custom/icu/public/components/display-by/display-by.js, packages/custom/icu/public/components/entity-list/entity-list.js, packages/custom/icu/public/components/task-list/task-list.js
without saving parent
https://github.com/linnovate/root/issues/1083
=> fixed creating subsidiary tasks from projects and discussions,

packages/custom/icu/public/components/entity-list/entity-list.js, packages/custom/icu/public/components/officeDocument-list/officeDocument-list.js
(cherry picked from commit 42210b4)
https://github.com/linnovate/root/issues/1097
=> fixed creation of 'officeDocument'

packages/custom/icu/public/components/folder-list/folder-list.js
https://github.com/linnovate/root/issues/1094
=> fixed creation of folder from office

packages/custom/icu/public/components/entity-list/entity-list.js, packages/custom/icu/public/components/entity-list/regions/filters.html, packages/custom/icu/public/components/task-list/task-list.js
https://github.com/linnovate/root/issues/1093
=> added excel button in task list

packages/custom/icu/public/components/modal-directive/modal.directive.js, packages/custom/icu/public/components/officeDocument-details/officeDocument-details.html
in opening officeDocuments modals
=> changed "officeDocument" value to "officeDocuments"

config/env/all.js, packages/custom/icu/public/components/folder-list/folder-list.js
fixed loading offices instead of folders in folders-list on scrolling
https://github.com/linnovate/root/issues/1108
=> fixed language bug,

packages/custom/icu/app.js, packages/custom/icu/public/components/details-components/detail-tabs/detail-tabs.js, packages/custom/icu/public/components/folder-list-directive/folder-list.directive.js, packages/custom/icu/public/components/folder-list-directive/folder-list.directive.template.html, packages/custom/icu/public/components/folder-list/folder-list.js, packages/custom/icu/public/components/office-details/office-details.html, packages/custom/icu/public/components/project-details/project-details.js
fixed showing folders in folders tab in offices
https://github.com/linnovate/root/issues/1109
=> fixed showing tasks in tasks tab in the projects,

packages/custom/icu/server/controllers/elasticsearch.js, packages/custom/icu/server/models/attachment.js, packages/custom/icu/server/models/comment.js, packages/custom/icu/server/models/discussion.js, packages/custom/icu/server/models/document.js, packages/custom/icu/server/models/folder.js, packages/custom/icu/server/models/office.js, packages/custom/icu/server/models/project.js, packages/custom/icu/server/models/task.js, packages/custom/icu/server/models/update.js
Refactor to the Elasticsearch save, delete and buildSearchResponse.
In addition i removed unnecessary parameters from the models using Elasticsearch to match the refactored functions.
=> Refactor elasticsearch

packages/custom/icu/public/components/folder-list/folder-list.js
(cherry picked from commit f6b8f83)
=> resolved issue with none-saving folders below the 25-th

packages/custom/icu/public/components/officeDocument-list/officeDocument-list.js
https://github.com/linnovate/root/issues/1127
=> fixed showing officeDocuments after 25th, and saving them

packages/custom/icu/public/components/folder-details/folder-details.js
(cherry picked from commit 5c720d8)
=> fixed showing tags of previous folder to current

packages/custom/icu/public/components/task-details/task-details.js
https://github.com/linnovate/root/issues/1136
=> fixed restoring task

packages/custom/icu/public/components/project-details/project-details.js
https://github.com/linnovate/root/issues/1112
=> fixed bug with saving old color

packages/custom/icu/public/assets/css/_detailspane.scss, packages/custom/icu/public/assets/css/_sub-projects.scss, packages/custom/icu/public/assets/css/_sub-tasks.scss, packages/custom/icu/public/assets/css/entity-details/_detail-due.scss, packages/custom/icu/public/components/details-components/detail-due/detail-due.js
https://github.com/linnovate/root/issues/1134
=> fixed bug with not-showed error warning that time is passed

packages/custom/icu/server/controllers/users.js
https://github.com/linnovate/root/issues/1055
=> fixed bug with saving new email and name of user in profile modal

packages/custom/icu/public/components/detailspane/detailspane.directive.js, packages/custom/icu/public/components/task-details/task-details.js
fixed creating entities from parents without saving parent
https://github.com/linnovate/root/issues/1088
=> fixed jumping to first item in the list on starring item,

packages/custom/icu/public/components/project-details/project-details.js
https://github.com/linnovate/root/issues/1112
=> fixed bug with not saving color

packages/custom/icu/public/components/task-details/task-details.js
https://github.com/linnovate/root/issues/1088
=> fixed jumping to first item in the list on starring item

packages/custom/icu/public/components/task-list/task-list.js
https://github.com/linnovate/root/issues/1183
=> fixed showing subs twice

packages/custom/icu/public/components/data/context/context.service.js
https://github.com/linnovate/root/issues/1060
=> fixed title in sub projects

packages/custom/icu/public/assets/css/_discussion-details.scss, packages/custom/icu/public/assets/css/entity-details/_detail-assign.scss, packages/custom/icu/public/assets/css/entity-details/_detail-color.scss, packages/custom/icu/public/assets/css/entity-details/_detail-due.scss, packages/custom/icu/public/assets/css/entity-details/_detail-favorite.scss, packages/custom/icu/public/assets/css/entity-details/_detail-menu.scss, packages/custom/icu/public/assets/css/entity-details/_detail-status.scss, packages/custom/icu/public/components/details-components/detail-menu/detail-menu.html, packages/custom/icu/public/components/project-details/project-details.html, packages/custom/icu/public/components/project-details/project-details.js
https://github.com/linnovate/root/issues/1197
=> design upgrade details header

packages/custom/icu/public/components/data/bulk-operations/bulk-operations.service.js, packages/custom/icu/public/components/discussion-list/discussion-list.js, packages/custom/icu/public/components/entity-list/entity-list.js, packages/custom/icu/public/components/entity-list/regions/filters.html, packages/custom/icu/public/components/entity-list/regions/list.html, packages/custom/icu/public/components/folder-list/folder-list.js, packages/custom/icu/public/components/office-list/office-list.js, packages/custom/icu/public/components/officeDocument-list/officeDocument-list.js, packages/custom/icu/public/components/project-list/project-list.js, packages/custom/icu/public/components/task-list/task-list.js, packages/custom/icu/public/components/templateDoc-list/templateDoc-list.js
https://github.com/linnovate/root/issues/1196
=> fixed showing entities after 25th

packages/core/system/server/controllers/index.js, packages/custom/icu/public/components/data/discussions/discussions.service.js, packages/custom/icu/public/components/data/projects/projects.service.js, packages/custom/icu/public/components/details-components/detail-hi/detail-hi.js, packages/custom/icu/public/components/discussion-details/discussion-details.html, packages/custom/icu/public/components/discussion-details/discussion-details.js, packages/custom/icu/public/components/folder-details/folder-details.html, packages/custom/icu/public/components/folder-details/folder-details.js, packages/custom/icu/public/components/office-details/office-details.html, packages/custom/icu/public/components/office-details/office-details.js, packages/custom/icu/public/components/project-details/project-details.html, packages/custom/icu/public/components/project-details/project-details.js, packages/custom/icu/server/controllers/notification.js, packages/custom/icu/server/models/discussion.js, packages/custom/icu/server/models/folder.js, packages/custom/icu/server/models/office.js, packages/custom/icu/server/models/project.js, packages/custom/icu/server/routes/icu.js
Shouldnt work outside - set config of rocketChat to active: false
would not work because of service(NodeModule) is missing...
=> RocketChat refactor

packages/custom/icu/public/components/task-details/task-details.js
https://github.com/linnovate/root/issues/1276
=> duplicate task: title, description, due date

packages/custom/icu/public/components/data/attachments/attachments.service.js, packages/custom/icu/public/components/data/discussions/discussions.service.js, packages/custom/icu/public/components/data/inbox/inbox.service.js, packages/custom/icu/public/components/tabs/activities/activities.directive.js, packages/custom/icu/server/controllers/attachments.js, packages/custom/icu/server/routes/icu.js
https://github.com/linnovate/root/issues/1351
=> fixed showing attachments after refreshing the page,

packages/custom/icu/docs/models.js, packages/custom/icu/public/assets/css/_detailspane.scss, packages/custom/icu/public/assets/css/_entity-list.scss, packages/custom/icu/public/assets/css/_modal.scss, packages/custom/icu/public/assets/css/_panes.scss, packages/custom/icu/public/assets/css/_sub-projects.scss, packages/custom/icu/public/assets/css/_sub-tasks.scss, packages/custom/icu/public/assets/css/_tabs-folders.scss, packages/custom/icu/public/assets/css/_tabs-officeDocuments.scss, packages/custom/icu/public/assets/css/_tabs-tasks.scss, packages/custom/icu/public/assets/css/entity-details/_detail-status.scss, packages/custom/icu/public/assets/locales/en/translation.json, packages/custom/icu/public/assets/locales/he/translation.json, packages/custom/icu/public/components/data/settings/settings.service.js, packages/custom/icu/public/components/entity-list/entity-list.filter.js, packages/custom/icu/public/components/entity-list/entity-list.js, packages/custom/icu/public/components/folder-details/folder-details.js, packages/custom/icu/public/components/office-details/office-details.js, packages/custom/icu/public/components/project-details/project-details.js, packages/custom/icu/public/components/templateDoc-details/templateDoc-details.js, packages/custom/icu/server/models/folder.js, packages/custom/icu/server/models/office.js, packages/custom/icu/server/models/project.js
https://github.com/linnovate/root/issues/1355
=> Changed all "Complete" status references to "Done".

packages/custom/icu/public/components/officeDocument-details/officeDocument-details.html, packages/custom/icu/public/components/officeDocument-details/officeDocument-details.js, packages/custom/icu/server/models/document.js
https://github.com/linnovate/root/issues/1354
=> removed relation to one task in officeDocuments entities,

packages/custom/icu/public/components/data/inbox/inbox.service.js, packages/custom/icu/public/components/details-components/detail-tabs/detail-tabs.js, packages/custom/icu/public/components/entity-list/entity-list.js, packages/custom/icu/public/components/tabs/documents/documents.directive.js
fixed selecting entity from the list on changing sub menu page,
https://github.com/linnovate/root/issues/1327
=> fixed sorting by 'star',

packages/custom/icu/public/components/modal-directive/bulkOperations/bulk-operationsController.js
https://github.com/linnovate/root/issues/1356
=> fixed showing statuses which are relevant to selected entities types,

packages/custom/icu/public/assets/css/entity-details/_detail-category.scss, packages/custom/icu/public/assets/css/mixins/_disable-text-styles.scss
=> removed styles for detail-category

packages/custom/icu/public/components/officeDocument-list/officeDocument-list.js, packages/custom/icu/server/controllers/documents.js
=> fixed creating office document from task with watchers of parent

packages/custom/icu/public/components/officeDocument-details/officeDocument-details.js, packages/custom/icu/server/controllers/documents.js, packages/custom/icu/server/models/document.js
=> fixed adding assignee as watcher on assign

packages/custom/icu/public/components/data/officeDocuments/officeDocuments.service.js, packages/custom/icu/server/controllers/documents.js
=> fixed changing document's watcher's permissions saving

packages/custom/icu/public/components/task-options/task-options.js
fixed need to click twice to see my tasks filtered results
=> fixed need to click twice to see "My tasks" filtering results

packages/custom/icu/public/components/search-list/search-list.directive.js
=> fixed that tick after bulk operation don't disabling

packages/custom/icu/public/components/row-types/search-discussion-row.html, packages/custom/icu/public/components/row-types/search-folder-row.html, packages/custom/icu/public/components/row-types/search-office-row.html, packages/custom/icu/public/components/row-types/search-officeDocument-row.html, packages/custom/icu/public/components/row-types/search-project-row.html, packages/custom/icu/public/components/row-types/search-task-row.html, packages/custom/icu/public/components/row-types/search-templateDoc-row.html
=> Fix wrong indexes in search list

packages/custom/icu/public/assets/css/entity-details/_detail-category.scss
=> fixed max size of entities categories

packages/custom/icu/public/components/entity-list/entity-list.js
=> fixed selection fo all entities in the list of tasks from parent

packages/custom/icu/server/controllers/task.js, packages/custom/icu/server/routes/icu.js
=> fixed adding watchers from officeDocument to child tasks

packages/custom/icu/server/controllers/task.js
=> fixed long creation of the task

packages/custom/icu/public/components/discussion-details/discussion-details.html, packages/custom/icu/public/components/discussion-details/discussion-details.js
=> fixed discussions due data ui issue

packages/custom/icu/public/components/officeDocument-details/officeDocument-details.js
=> fixed showing permissions and watchers to child document from folder

packages/custom/icu/public/components/modal-directive/bulkOperations/bulk-operationsController.js
=> fixed bulk dueDate checks for past date to prevent updating

packages/custom/icu/public/components/notifications-header/header.directive.js, packages/custom/icu/server/controllers/documents.js
from plus menu,
fixed saving officeDocs to tasks mongo $pushAll issue,
#1613
=> fixed opening the same list by managing officeDocs and creating doc

packages/custom/icu/public/components/details-components/detail-due/detail-due.js
=> Fix date casting

packages/custom/icu/public/components/data/tasks/tasks.service.js, packages/custom/icu/server/controllers/documents.js, packages/custom/icu/server/controllers/star.js, packages/custom/icu/server/routes/icu.js, packages/custom/icu/server/services/star.js
=> fixed filtering by star in tasks by officeDocument,

packages/custom/icu/public/app/app.js, packages/custom/icu/public/components/project-details/project-details.js
=> Added subProjects to project details on search

packages/custom/icu/server/controllers/documents.js
=> Fix prevent adding existing assignee to watchers

packages/custom/icu/public/components/entity-list/entity-list.js
=> fixed changing order of officeDocument list after creation of new doc,

packages/custom/icu/public/components/entity-list/entity-list.js, packages/custom/icu/public/components/entity-list/regions/header.html
=> added name of parent entity in "byentity" pages

packages/custom/icu/public/assets/css/_tabs-activities.scss, packages/custom/icu/public/assets/css/_tabs-documents.scss, packages/custom/icu/public/assets/css/entity-details/_entity-details.scss, packages/custom/icu/public/components/officeDocument-details/officeDocument-details.html
=> Fix CSS show display activities

packages/custom/icu/public/components/data/tasks/tasks.service.js, packages/custom/icu/server/controllers/task.js
feature:
when a user tries to download an excel report for tasks when he is under tasks by projects\meetings,
the generated excel will contain only the tasks from that entity.
=> feat: deep link excel
